server:
  port: 8080
  address: 0.0.0.0
spring:
  data:
    mongodb:
      uri: mongodb://root:2904@localhost:27018/service_be?authSource=admin
      auto-index-creation: true
      connection-pool:
        max-size: 200
        min-size: 50
        max-wait-time: 5000
    redis:
      host: localhost
      port: 6379
      password: 2904
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: elasticsearch:9200
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
  jwt:
    secret:
      token: X7L09tGUn1wY1bU4fXdZc+PVKJyZ1fcryMO69DB0b7RbP9VTOTBaLYkW8PgVw0Ry2iyP9nwODpTvOr6NgPPf6A==
    expire:
      token: 1209600000
      refresh: 2592000000
  cloudinary:
    cloudName: dbk09oy6h
    apiKey: 284342617128334
    apiSecret: QU27UPSU5A8u5vIiYGBl2rl1DwU
url:
  api:
    prefix: /api/v1
logging:
  level:
    org.springframework.data.mongodb: DEBUG
email:
  api:
    url: https://api.brevo.com/v3/smtp/email
    key: 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
